---
- name: Setup trustbox builder instance
  hosts: all
  tasks:
    - name: Add Hashicorp GPG key
      become: true
      apt_key:
        url: "https://apt.releases.hashicorp.com/gpg"
        state: present
    - name: Add Hashicorp APT repository
      become: true
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes
    - name: Install necessary packages
      become: true
      apt:
        name:
          - qemu-system-x86
          - packer
          - tmux
          - cpu-checker # For kvm-ok command
        state: present
    - name: Check if KVM is available
      become: true
      command: kvm-ok
      register: kvm_check
      ignore_errors: true
    - name: Add user to kvm group if KVM is available
      become: true
      user:
        name: "{{ ansible_user }}"
        groups: kvm
        append: yes
      when: kvm_check.rc == 0
    - name: Create directory for Trustbox
      become: true
      file:
        path: /opt/trustbox
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
    - name: Generate Trustbox SSH key
      ansible.builtin.openssh_keypair:
        path: /opt/trustbox/id_rsa
        comment: trustbox-rsa-key
      register: trustbox_ssh_key
    - name: Create cloud-init configuration directory
      file:
        path: /opt/trustbox/cloud-init
        state: directory
    - name: Copy cloud-init meta-data
      copy:
        src: files/cloud-init/meta-data
        dest: /opt/trustbox/cloud-init/
        mode: "0644"
    - name: Prepare cloud-init user-data
      vars:
        vm_ssh_public_key: "{{ trustbox_ssh_key.public_key }}"
      template:
        src: templates/cloud-init/user-data.j2
        dest: /opt/trustbox/cloud-init/user-data
        mode: "0644"
    - name: Prepare Packer template
      vars:
        vm_accelerator: "{{ 'kvm' if kvm_check.rc == 0 else 'none' }}"
      template:
        src: templates/packer/vm.pkr.hcl.j2
        dest: /opt/trustbox/vm.pkr.hcl
        mode: "0644"
    - name: Install Packer plugins
      command: packer plugins install github.com/hashicorp/qemu
      args:
        chdir: /opt/trustbox
