---
- name: Setup trustbox builder instance
  hosts: all
  tasks:
    - name: Validate SSH public key
      ansible.builtin.assert:
        that:
          - vm_ssh_public_key.startswith('ssh-rsa ')
        fail_msg: SSH public key must start with 'ssh-rsa ', as it's used for Dropbear SSH server during the boot.
    - name: Add Hashicorp GPG key
      become: true
      apt_key:
        url: "https://apt.releases.hashicorp.com/gpg"
        state: present
    - name: Add Hashicorp APT repository
      become: true
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes
    - name: Install necessary packages
      become: true
      apt:
        name:
          - qemu-system-x86
          - packer
          - cloud-image-utils
        state: present
    - name: Create directory for ISO files
      become: true
      file:
        path: /opt/trustbox
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"
    - name: Create cloud-init configuration directory
      file:
        path: /opt/trustbox/cloud-init
        state: directory
    - name: Copy cloud-init meta-data
      copy:
        src: files/cloud-init/meta-data
        dest: /opt/trustbox/cloud-init/
        mode: "0644"
    - name: Prepare cloud-init user-data
      template:
        src: templates/cloud-init/user-data.j2
        dest: /opt/trustbox/cloud-init/user-data
        mode: "0644"
    - name: Create cloud-init ISO
      command: cloud-localds -v /opt/trustbox/cloud-init.iso /opt/trustbox/cloud-init/user-data /opt/trustbox/cloud-init/meta-data && shred /opt/trustbox/cloud-init/user-data
    - name: Prepare Packer template
      template:
        src: templates/packer/trustbox.pkr.hcl
        dest: /opt/trustbox/build.pkr.hcl
        mode: "0644"
    - name: Install Packer plugins
      command: packer plugins install github.com/hashicorp/qemu
      args:
        chdir: /opt/trustbox
